# Kover configuration for Kotlin project
kover:
  # Define the type of coverage report
  reports:
    xml:
      enabled: true
      outputDir: build/reports/kover/xml
    html:
      enabled: true
      outputDir: build/reports/kover/html
    css:
      enabled: false
    json:
      enabled: false

  # Customize the thresholds for coverage
  thresholds:
    rule:
      minLineCoverage: 80
      minBranchCoverage: 80
      minFunctionCoverage: 80
      minClassCoverage: 80